---
title: "Hands-On Exercise 2:</br>Beyond ggplot2 Fundamentals"
author: "CHUA Wee Tian"
date: "April 18, 2026"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## 2.1 Learning Objectives

By the end of this exercise, you will be able to:

-   control the placement of annotation on a graph by using functions provided in ggrepel package

-   create professional publication quality figure by using functions provided in ggthemes and hrbrthemes packages

-   plot composite figure by combining ggplot2 graphs by using patchwork package

## 2.2 Getting started

### 2.2.1 Installing and loading the required libraries

Besides tidyverse, the following R packages will be used.

ggrepel: an R package provides geoms for ggplot2 to repel overlapping text labels.

ggthemes: an R package provides some extra themes, geoms, and scales for ‘ggplot2’.

hrbrthemes: an R package provides typography-centric themes and theme components for ggplot2.

patchwork: an R package for preparing composite figure created using ggplot2.

Code chunk below will be used to check if these packages have been installed and also will load them into the working R environment.

```{r}
pacman::p_load(ggrepel, patchwork, 
               ggthemes, hrbrthemes,
               tidyverse)
```

### 2.2.2 Importing data

